version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - aws cloudformation package --template-file infrastructure.yml --s3-bucket codepipeline-eu-central-1-169093108018 --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml
